name: street-network

channels:
  - conda-forge

dependencies:
  - matplotlib=3.8.4
  - pandas=1.5.3
  - numpy=1.23.5
  - geopandas=0.9.0
  - pip=23.0.1
  - python=3.10.10
  - fiona=1.9.2
  - shapely=2.0.1
  - networkx=3.2.1
  - pyproj=3.6.1
  - scikit-spatial=6.8.1